apiVersion: v1
kind: Service
metadata:
  name: healthcare-gateway
  namespace: healthcare-federation
  labels:
    app: healthcare-gateway
    component: graphql-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: healthcare-gateway