apiVersion: v1
kind: Service
metadata:
  name: institutions-service
  namespace: healthcare-federation
  labels:
    app: institutions-service
    component: graphql-subgraph
spec:
  type: ClusterIP
  ports:
  - port: 4005
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: institutions-service