apiVersion: v1
kind: Service
metadata:
  name: patients-service
  namespace: healthcare-federation
  labels:
    app: patients-service
    component: graphql-subgraph
spec:
  type: ClusterIP
  ports:
  - port: 4002
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: patients-service